In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
train_df = pd.read_csv('train_jqd04QH.csv')
test_df = pd.read_csv('test_KaymcHn.csv')

train_df.head()

enrollee_id      city  city_development_index gender  \
0        23798  city_149                   0.689   Male   
1        29166   city_83                   0.923   Male   
2           46   city_16                   0.910    NaN   
3        18527   city_64                   0.666   Male   
4        21751  city_100                   0.887    NaN   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1  Has relevent experience       no_enrollment        Graduate   
2  Has relevent experience       no_enrollment        Graduate   
3  Has relevent experience       no_enrollment        Graduate   
4   No relevent experience       no_enrollment         Masters   

  major_discipline experience company_size    company_type last_new_job  \
0             STEM          3      100-500         Pvt Ltd            1   
1             STEM         14          <10  Funded Startup            1   
2             STEM          6        50-99   Public Sector            2   
3             STEM         14        50-99         Pvt Ltd            1   
4             STEM          8          NaN             NaN            2   

   training_hours  target  
0             106       0  
1              69       0  
2               4       0  
3              26       0  
4              88       1

In [3]:
print(train_df.shape)
print(test_df.shape)

(18359, 14)
(15021, 13)


In [4]:
test_df.head()

enrollee_id      city  city_development_index gender  \
0        16548   city_33                   0.448    NaN   
1        12036   city_28                   0.939   Male   
2        11061  city_103                   0.920   Male   
3         5032  city_104                   0.924   Male   
4        17599   city_77                   0.830   Male   

       relevent_experience enrolled_university education_level  \
0   No relevent experience    Full time course        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   
3   No relevent experience       no_enrollment             Phd   
4  Has relevent experience       no_enrollment        Graduate   

  major_discipline experience company_size   company_type last_new_job  \
0             STEM         <1    1000-4999  Public Sector          NaN   
1             STEM        >20        50-99        Pvt Ltd            1   
2             STEM          3          NaN            NaN            1   
3             STEM        >20        50-99        Pvt Ltd            2   
4             STEM          6          <10        Pvt Ltd            2   

   training_hours  
0              15  
1              94  
2              17  
3              76  
4              65

In [5]:
(train_df.isna().sum()/ len(train_df.index) *100).sort_values(ascending=False).head()

company_type        27.447029
company_size        26.030830
gender              22.321477
major_discipline    15.458358
education_level      2.489242
dtype: float64

In [6]:
train_df = train_df[train_df['experience'].notna()]
train_df = train_df[train_df['enrolled_university'].notna()]
train_df = train_df[train_df['last_new_job'].notna()]
train_df = train_df[train_df['education_level'].notna()]

train_df['relevent_experience'] = train_df['relevent_experience'].apply(lambda x: 0 if x == 'No relevent experience' else 1)
train_df['last_new_job'] = train_df['last_new_job'].apply(lambda x: 0 if x == 'never' else x)
train_df['last_new_job'] = train_df['last_new_job'].apply(lambda x: 5 if x == '>4' else x)
train_df['experience'] = train_df['experience'].apply(lambda x: 0 if x == '<1' else x)
train_df['experience'] = train_df['experience'].apply(lambda x: 21 if x == '>20' else x)
train_df['city'] = train_df['city'].apply(lambda x: x.split('_')[1])
train_df['major_discipline'] = train_df['major_discipline'].apply(lambda x: 'No Major' if pd.isna(x) else x)

train_df['company_type'] = train_df['company_type'].fillna('Pvt Ltd')
train_df['company_size'] = train_df['company_size'].fillna('50-99')
train_df['gender'] = train_df['gender'].fillna('Male')

In [7]:
test_df['experience'] = test_df['experience'].fillna(21)
test_df['enrolled_university'] = test_df['enrolled_university'].fillna('no_enrollment')
test_df['last_new_job'] = test_df['last_new_job'].fillna(1)
test_df['education_level'] = test_df['education_level'].fillna('Graduate')

test_df['relevent_experience'] = test_df['relevent_experience'].apply(lambda x: 0 if x == 'No relevent experience' else 1)
test_df['last_new_job'] = test_df['last_new_job'].apply(lambda x: 0 if x == 'never' else x)
test_df['last_new_job'] = test_df['last_new_job'].apply(lambda x: 5 if x == '>4' else x)
test_df['experience'] = test_df['experience'].apply(lambda x: 0 if x == '<1' else x)
test_df['experience'] = test_df['experience'].apply(lambda x: 21 if x == '>20' else x)
test_df['city'] = test_df['city'].apply(lambda x: x.split('_')[1])
test_df['major_discipline'] = test_df['major_discipline'].apply(lambda x: 'No Major' if pd.isna(x) else x)

test_df['company_type'] = test_df['company_type'].fillna('Pvt Ltd')
test_df['company_size'] = test_df['company_size'].fillna('50-99')
test_df['gender'] = test_df['gender'].fillna('Male')

In [8]:
train_df.isna().sum().sum()

0

In [9]:
train_df.nunique(dropna=False).sort_values()

relevent_experience           2
target                        2
gender                        3
enrolled_university           3
education_level               5
major_discipline              6
company_type                  6
last_new_job                  6
company_size                  8
experience                   22
city_development_index       93
city                        123
training_hours              241
enrollee_id               17315
dtype: int64

In [10]:
(test_df.isna().sum()/ len(test_df.index) *100).sort_values(ascending=False).head()

training_hours    0.0
last_new_job      0.0
company_type      0.0
company_size      0.0
experience        0.0
dtype: float64

In [11]:
train_df.head()

enrollee_id city  city_development_index gender  relevent_experience  \
0        23798  149                   0.689   Male                    1   
1        29166   83                   0.923   Male                    1   
2           46   16                   0.910   Male                    1   
3        18527   64                   0.666   Male                    1   
4        21751  100                   0.887   Male                    0   

  enrolled_university education_level major_discipline experience  \
0       no_enrollment        Graduate             STEM          3   
1       no_enrollment        Graduate             STEM         14   
2       no_enrollment        Graduate             STEM          6   
3       no_enrollment        Graduate             STEM         14   
4       no_enrollment         Masters             STEM          8   

  company_size    company_type last_new_job  training_hours  target  
0      100-500         Pvt Ltd            1             106       0  
1          <10  Funded Startup            1              69       0  
2        50-99   Public Sector            2               4       0  
3        50-99         Pvt Ltd            1              26       0  
4        50-99         Pvt Ltd            2              88       1

In [12]:
test_df.isna().sum().sum()

0

In [13]:
columns = ['gender', 'enrolled_university', 'education_level', 'major_discipline', 'company_size', 'company_type']

train_df_one_hot = pd.get_dummies(train_df[columns], drop_first=True)
test_df__one_hot = pd.get_dummies(test_df[columns], drop_first=True)

train_df.drop(columns=columns, inplace=True)
test_df.drop(columns=columns, inplace=True)

train_df = train_df.join(train_df_one_hot)
test_df = test_df.join(test_df__one_hot)

In [14]:
train_df['experience'] = train_df['experience'].astype('int64')
test_df['experience'] = test_df['experience'].astype('int64')

train_df['last_new_job'] = train_df['last_new_job'].astype('int64')
test_df['last_new_job'] = test_df['last_new_job'].astype('int64')

In [15]:
train_df.head()

enrollee_id city  city_development_index  relevent_experience  experience  \
0        23798  149                   0.689                    1           3   
1        29166   83                   0.923                    1          14   
2           46   16                   0.910                    1           6   
3        18527   64                   0.666                    1          14   
4        21751  100                   0.887                    0           8   

   last_new_job  training_hours  target  gender_Male  gender_Other  ...  \
0             1             106       0            1             0  ...   
1             1              69       0            1             0  ...   
2             2               4       0            1             0  ...   
3             1              26       0            1             0  ...   
4             2              88       1            1             0  ...   

   company_size_10000+  company_size_50-99  company_size_500-999  \
0                    0                   0                     0   
1                    0                   0                     0   
2                    0                   1                     0   
3                    0                   1                     0   
4                    0                   1                     0   

   company_size_5000-9999  company_size_<10  company_type_Funded Startup  \
0                       0                 0                            0   
1                       0                 1                            1   
2                       0                 0                            0   
3                       0                 0                            0   
4                       0                 0                            0   

   company_type_NGO  company_type_Other  company_type_Public Sector  \
0                 0                   0                           0   
1                 0                   0                           0   
2                 0                   0                           1   
3                 0                   0                           0   
4                 0                   0                           0   

   company_type_Pvt Ltd  
0                     1  
1                     0  
2                     0  
3                     1  
4                     1  

[5 rows x 33 columns]

In [16]:
train_df_one_hot = pd.get_dummies(train_df['city'], drop_first=True)
test_df__one_hot = pd.get_dummies(test_df['city'], drop_first=True)

train_df.drop(columns='city', inplace=True)
test_df.drop(columns='city', inplace=True)

train_df = train_df.join(train_df_one_hot)
test_df = test_df.join(test_df__one_hot)

In [17]:
train_df.head()

enrollee_id  city_development_index  relevent_experience  experience  \
0        23798                   0.689                    1           3   
1        29166                   0.923                    1          14   
2           46                   0.910                    1           6   
3        18527                   0.666                    1          14   
4        21751                   0.887                    0           8   

   last_new_job  training_hours  target  gender_Male  gender_Other  \
0             1             106       0            1             0   
1             1              69       0            1             0   
2             2               4       0            1             0   
3             1              26       0            1             0   
4             2              88       1            1             0   

   enrolled_university_Part time course  ...  84  89  9  90  91  93  94  97  \
0                                     0  ...   0   0  0   0   0   0   0   0   
1                                     0  ...   0   0  0   0   0   0   0   0   
2                                     0  ...   0   0  0   0   0   0   0   0   
3                                     0  ...   0   0  0   0   0   0   0   0   
4                                     0  ...   0   0  0   0   0   0   0   0   

   98  99  
0   0   0  
1   0   0  
2   0   0  
3   0   0  
4   0   0  

[5 rows x 154 columns]

In [18]:
train_df.shape

(17315, 154)

In [19]:
test_df.shape

(15021, 153)

In [20]:
set(test_df.columns) - set(train_df.columns)

set()

In [21]:
test_df[['city_development_index', 'experience', 'last_new_job', 'training_hours' ]].describe()

city_development_index    experience  last_new_job  training_hours
count            15021.000000  15021.000000  15021.000000    15021.000000
mean                 0.846683     10.571333      2.037081       65.158179
std                  0.109709      6.800656      1.671336       59.719211
min                  0.448000      0.000000      0.000000        1.000000
25%                  0.794000      5.000000      1.000000       23.000000
50%                  0.910000      9.000000      1.000000       47.000000
75%                  0.920000     17.000000      3.000000       89.000000
max                  0.949000     21.000000      5.000000      336.000000

In [22]:
train_df['target'].value_counts()

0    15064
1     2251
Name: target, dtype: int64

In [23]:
X_train = train_df.drop('target', axis=1)
y_train = train_df['target']

X_test = test_df.copy()

In [24]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_recall_curve, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


lr = LogisticRegression()
lr.fit(X_train, y_train)

y_train_pred = lr.predict(X_train)

print(accuracy_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))

0.8699971123303494
0.0
0.0


In [25]:
rfc = RandomForestClassifier(n_estimators=10)

rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_train)

print(accuracy_score(y_train, rfc_pred))
print(f1_score(y_train, rfc_pred))
print(recall_score(y_train, rfc_pred))

rfc_test_pred = rfc.predict(X_test)

0.9770719029742997
0.9033357682006331
0.8240781874722346


In [26]:
rfc_test_pred

array([1, 0, 0, ..., 0, 0, 0])

In [27]:
rfc_test_pred_proba = rfc.predict_proba(X_test)[:,1]

In [39]:
rfc_test_pred

array([1, 0, 0, ..., 0, 0, 0])

In [28]:
submission = pd.read_csv('sample_submission_sxfcbdx.csv')
submission.head()

enrollee_id  target
0        16548       0
1        12036       0
2        11061       0
3         5032       0
4        17599       0

In [57]:
submission['target'] = rfc_test_pred_proba

In [58]:
submission['target'].value_counts()

0.0    5325
0.1    4409
0.2    2594
0.3    1407
0.4     745
0.5     295
0.6     152
0.7      63
0.8      24
0.9       6
1.0       1
Name: target, dtype: int64

In [59]:
submission.to_csv('rfc_proba.csv',index = False)

In [60]:
pd.read_csv('rfc_proba.csv')

enrollee_id  target
0            16548     0.6
1            12036     0.0
2            11061     0.4
3             5032     0.0
4            17599     0.0
...            ...     ...
15016        11308     0.2
15017        14612     0.4
15018        33346     0.2
15019        14506     0.2
15020        32641     0.3

[15021 rows x 2 columns]

In [34]:
test_df.head()

enrollee_id  city_development_index  relevent_experience  experience  \
0        16548                   0.448                    0           0   
1        12036                   0.939                    0          21   
2        11061                   0.920                    0           3   
3         5032                   0.924                    0          21   
4        17599                   0.830                    1           6   

   last_new_job  training_hours  gender_Male  gender_Other  \
0             1              15            1             0   
1             1              94            1             0   
2             1              17            1             0   
3             2              76            1             0   
4             2              65            1             0   

   enrolled_university_Part time course  enrolled_university_no_enrollment  \
0                                     0                                  0   
1                                     0                                  1   
2                                     0                                  0   
3                                     0                                  1   
4                                     0                                  1   

   ...  84  89  9  90  91  93  94  97  98  99  
0  ...   0   0  0   0   0   0   0   0   0   0  
1  ...   0   0  0   0   0   0   0   0   0   0  
2  ...   0   0  0   0   0   0   0   0   0   0  
3  ...   0   0  0   0   0   0   0   0   0   0  
4  ...   0   0  0   0   0   0   0   0   0   0  

[5 rows x 153 columns]

In [29]:
test_df.shape

(15021, 153)

In [30]:
submission.shape

(15021, 2)

In [31]:
from sklearn.utils import resample

looking_for_job = train_df[train_df['target'] == 1] # minority category
not_looking_for_job = train_df[train_df['target'] == 0]

looking_for_job_upsampled = resample(looking_for_job, replace = True, 
                                     n_samples = len(not_looking_for_job), random_state = 27)

upsampled = pd.concat([not_looking_for_job, looking_for_job_upsampled])

upsampled['target'].value_counts()

1    15064
0    15064
Name: target, dtype: int64

In [32]:
X_train = upsampled.drop('target', axis=1)
y_train = upsampled['target']

upsample_lr = LogisticRegression()
upsample_lr.fit(X_train, y_train)

upsample_lr_pred = upsample_lr.predict(X_train)

print(accuracy_score(y_train, upsample_lr_pred))
print(f1_score(y_train, upsample_lr_pred))
print(recall_score(y_train, upsample_lr_pred))

0.5974508762612852
0.6056960790688601
0.6183616569304302


In [61]:
upsample_lr_test_pred = upsample_lr.predict_proba(X_test)

In [62]:
upsample_lr_test_pred

array([[0.39237054, 0.60762946],
       [0.5216604 , 0.4783396 ],
       [0.30341567, 0.69658433],
       ...,
       [0.61567917, 0.38432083],
       [0.33170469, 0.66829531],
       [0.36942088, 0.63057912]])

In [63]:
submission['target'] = upsample_lr_test_pred

submission['target'].value_counts()

submission.to_csv('lr_proba.csv',index = False)

pd.read_csv('lr_proba.csv')

enrollee_id    target
0            16548  0.392371
1            12036  0.521660
2            11061  0.303416
3             5032  0.498046
4            17599  0.525679
...            ...       ...
15016        11308  0.566700
15017        14612  0.455895
15018        33346  0.615679
15019        14506  0.331705
15020        32641  0.369421

[15021 rows x 2 columns]

In [33]:
from imblearn import SMOTE

sm = SMOTE(random_state=27, ratio=0.1)
X_train, y_train = sm.fit_sample(X_train, y_train)

smote_lr = LogisticRegression()
smote_lr.fit(X_train, y_train)
smote_lr_pred = smote_lr.predict(X_train)

print(accuracy_score(y_train, smote_lr_pred))
print(f1_score(y_train, smote_lr_pred))
print(recall_score(y_train, smote_lr_pred))

Using TensorFlow backend.


ImportError: cannot import name 'SMOTE' from 'imblearn' (/usr/local/lib/python3.7/site-packages/imblearn/__init__.py)

In [49]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

principalComponents = pca.fit_transform(X_train)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [50]:
pca.explained_variance_ratio_

array([9.99958842e-01, 4.06022654e-05])

In [51]:
test_pca = pca.transform(X_test)

In [52]:
pca_lr = LogisticRegression()
pca_lr.fit(principalComponents, y_train)

pca_train_pred = pca_lr.predict(principalComponents)

print(accuracy_score(y_train, pca_train_pred))
print(f1_score(y_train, pca_train_pred))
print(recall_score(y_train, pca_train_pred))

0.5217737652681891
0.5239228125826064
0.5262878385554965


In [53]:
pca_test_pred = pca_lr.predict(test_pca)

In [54]:
pca_test_pred

array([0, 0, 0, ..., 1, 0, 1])

In [56]:
submission['target'] = pca_test_pred

submission['target'].value_counts()

submission.to_csv('pca_lr.csv',index = False)

pd.read_csv('pca_lr.csv')

enrollee_id  target
0            16548       0
1            12036       0
2            11061       0
3             5032       0
4            17599       1
...            ...     ...
15016        11308       0
15017        14612       0
15018        33346       1
15019        14506       0
15020        32641       1

[15021 rows x 2 columns]

In [65]:
import re

regex = re.compile(r"\[|\]|<", re.IGNORECASE)

X_train.columns = [regex.sub("_", col) if any(x in str(col) for x in set(('[', ']', '<'))) else col for col in X_train.columns.values]


In [66]:
X_test.columns = [regex.sub("_", col) if any(x in str(col) for x in set(('[', ']', '<'))) else col for col in X_test.columns.values]


In [67]:
from xgboost import XGBClassifier

xgb = XGBClassifier()
xgb.fit(X_train, y_train)

xgb_train_pred = xgb.predict(X_train)

print(accuracy_score(y_train, xgb_train_pred))
print(f1_score(y_train, xgb_train_pred))
print(recall_score(y_train, xgb_train_pred))

0.6580589484864577
0.6397398237515736
0.6072092405735529


In [69]:
xgb_test_pred = xgb.predict(X_test)
submission['target'] = xgb_test_pred

submission['target'].value_counts()

submission.to_csv('xgb.csv',index = False)

pd.read_csv('xgb.csv')

enrollee_id  target
0            16548       1
1            12036       0
2            11061       1
3             5032       0
4            17599       0
...            ...     ...
15016        11308       0
15017        14612       1
15018        33346       0
15019        14506       1
15020        32641       1

[15021 rows x 2 columns]

### Questions

- What happens if there are no missing data in training set and we train a model and we get a missing value in test data? For eg: In relevant experience we have only two values, yes or no. We standaridise it acc to this and later if it changes or null data appears in test data

